baseURL = 'https://salpiras.github.io/'
languageCode = 'en-uk'
title = 'Sal on mobile'

[module]
  # uncomment line below for temporary local development of module
  # replacements = "github.com/lxndrblz/anatole -> ../../anatole"
  [[module.imports]]
    path = "github.com/lxndrblz/anatole"
    disable = false

[params]
title = "Salvatore Piras"
author = "Salvatore Piras"
description = "Ramblings on mobile and beyond"
profilePicture = "images/gh-profile.png"