baseURL = "https://example.com"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Sal's all things mobile"
theme = 'Anatole'

summarylength = 10
enableEmoji = true
enableRobotsTXT = true

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
        unsafe=true

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"

[params]
title = "Salvatore Piras"
author = "Salvatore Piras"
#copyright = "2023"
description = "Ramblings on all things mobile and beyond"
profilePicture = "images/gh-profile.png"

reversepagetitle = true


[[params.socialIcons]]
icon = "fab fa-github"
title = "Github"
url = "https://github.com/salpiras"

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/salvatore-piras-3894b694"

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

#  [[menu.main]]
#  name = "CV"
#  weight = 300
#  identifier = "portfolio"
#  url = "/portfolio/"

  [[menu.main]]
  name = "About"
  weight = 400
  identifier = "about"
  url = "/about/"